# versao 10
FROM debian:buster

RUN apt update \
    && apt install mariadb-server -y

COPY ./tools/script.sh .

# Copia o arquivo de configuração
COPY ./tools/db_script.sql /etc/mysql/conf.d/

# Substitui as variáveis de ambiente no arquivo de configuração

WORKDIR /var/lib/mysql

#RUN service mysql start --bind=0.0.0.0

ENTRYPOINT ["bash", "-c", "/script.sh"]

#ENTRYPOINT ["sh", "-c", "tail -f /dev/null"]