# versao 10
FROM debian:buster

# 1 && 2- update e instalar o nginx 
# 3- limpar o cache do gerenciador
RUN apt update \
    && apt install nginx -y \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# EXPOSE 80

# EXPOSE 9000

# EXPOSE 443

# O ENTRYPOINT que está no github
CMD ["nginx", "-g", "daemon off;"]
